---
$schemaver: '2.0'
deployables:
  - name: byu_ws_cli
    type: Command-line App
    aliases:
    short_description: A command-line web service client for calling BYU REST web
        services.
    assignment_group: AD-Student Life Applications
    notes:
    maintained_by:
      - Paul Eden
    developed_by_byu: true
    ddd:
        business_domain:
        ubiquitous_language_url:
        context_map_url:
    links:
        system_documentation_url: https://github.com/byu-oit-appdev/byu-ws-cli-python
        source_repo_url: https://github.com/test-ndpete-org/byu-ws-cli-python
        swagger_urls:
    microservice: false
    technologies_used:
      - Python
      - OIT Custom Web Service Authentication
      - REST Web Services
    stages:
        production:
            urls:
                product_page: https://pypi.python.org/pypi/byu_ws_cli
                physical_url:
                virtual_url:
            hosting_location: Other
            aws_account:
            relationships:
                depends_on:
                    db_read_write:
                    db_read_only:
                    software:
                      - byu_ws_sdk
                supports:
                    software:
                    service:
                reverse_proxy:
                runs_on:
                    server_cluster:
                    virtual_server:
                    rack_server:
                    blade_server:
    tags:
        data-sensitivity: Not Classified
        env: production
        team:
        app: byu_ws_cli
    federation_json_url: https://raw.githubusercontent.com/test-ndpete-org/byu-ws-cli-python/master/.repo-meta.yml
    x-anything:
